### ISSUE TITLE
unable to use the server/client application

### ISSUE THREAD

**Issue by laurentvinc** [IBM/fabcar-blockchain-sample#2]
everything sound correct, I created the network using IPB 2.0. when I start the server, i am getting "clien.JS: Channel not found for the name mychannel.
![image](https://user-images.githubusercontent.com/40390421/53739384-e7b3a180-3e91-11e9-9c65-e95434dcff14.png)
I checked the settings of my platform and 'mychannel' is there.
Do you have any Idea? do you more details?

**Comment by harsha544** [comment]
+1 I have faced the same issue, couldn't find a fix. 
Had to start afresh from ground up.

**Comment by ljbennett62** [comment]
@laurentvinc @harsha544 - you can actually ignore that error - it isn't really an error - you should still be able to see the blocks on the ledger.  The Blockchain team is aware of this - but is not a showstopper.
