### ISSUE TITLE
Can not run createCar function

### ISSUE THREAD

**Issue by SatoshiNishishita** [IBM/fabcar-blockchain-sample#21]
Hello. I found a bug web-app/server/app.js line27
We can not run createCar because of this bug.
Incorrect：var carsRecord = JSON.parse(JSON.parse(response));
correct：var carsRecord = JSON.parse(response);

Please modify this code.
Thank you.

**Comment by sandhya-nayak** [comment]
@SatoshiNishishita Thank you for identifying and reporting this. Looks like the JSON api has had an update since this repo was created. We've had to update many other repos with a similar change. I'll add the fix.

**Comment by sandhya-nayak** [comment]
@SatoshiNishishita The fix has been merged in.
