### ISSUE TITLE
error in Start the application server

### ISSUE THREAD

**Issue by jaffaszt** [IBM/fabcar-blockchain-sample#3]
I managed to run all the steps 1-6 with success
on Step 7 ran Enroll admin and Register User steps both with success but when I ran "npm start "
I got an error .... (I am running Windows 7 )
![image](https://user-images.githubusercontent.com/12609950/53885520-a0124e80-4026-11e9-841b-476d8795a8cb.png)

**Comment by mikiquet** [comment]
I have the same error, please if somebody knows how to solve it would be a great help. Tanks!

**Comment by ljbennett62** [comment]
@jaffaszt @mikiquet  - which version of npm are you running. YOu should be at 5.5.1

**Comment by jaffaszt** [comment]
@ljbennett62 I have npm 6.9.0 and using Windows 7 - it seems that the script is no migrated properly to windows

**Comment by mikiquet** [comment]
im running with 6.4.1, i have to change it?

**Comment by ljbennett62** [comment]
@jaffaszt @mikiquet - you both pulled the latest code? - updates were made late last week.

**Comment by mikiquet** [comment]
yes i tried with the latest code, and run npm 5.5.1 and the problem persist...

**Comment by ljbennett62** [comment]
@mikiquet - which version of node are you running - I am running 8.9.0. i just downloaded the code again, set up a brand new instance of Kub + Blockchain and ran the app and all works fine.

**Comment by ljbennett62** [comment]
@mikiquet @jaffaszt - try this: go into the file `colors.scss` - it is in the `web-app/client/src/` directory.  Change the `C`to lower case in the import stmt and re-run `npm start`.  I think similar to someone else - you may be experiencing case sensitivity.  I have updated the file in the repo - but test this theory out on your own machines.
