### ISSUE TITLE
gatewayDiscovery

### ISSUE THREAD

**Issue by henghengxqc** [IBM/fabcar-blockchain-sample#5]
I'm the IBM Blockchain Platform SRE. I tried this sample to interact with IPB v2. I works find and the document of this sample is very detailed.

However, when our customers of IBP try this sample, some of them encounter the "discovery error:access denied" error. After our investigation, it's because they didn't set the gatewayDiscovery properly base on your document.

Instead of 'fabric-client' API, the fabcar sample utilizes the high level 'fabric-network' to interact with smart contracts, which is a new feature in fabric-node-sdk 1.4. Some of the customer were not aware of that. So they choose to ignore it.

My proposal is, could you please document a little bit more about gatewayDiscovery or highlight gatewayDiscovery is required. So the users will not ignore it.

Many thanks.

**Comment by ljbennett62** [comment]
@henghengxqc - updating repo now - will add this in - thank you for sharing....

**Comment by ljbennett62** [comment]
@henghengxqc - i have added the text in the troubleshooting section.
