### ISSUE TITLE
Client GUI is Based on Angular now, not Vue 

### ISSUE THREAD

**Issue by jsolderitsch** [IBM/fabcar-blockchain-sample#8]
The README says the web client is based on Vue JS framework but as of 16 days ago(?) it seems the basis for the client was switched to Angular. The documentation needs adjustment. The client is on port 4200 as a result and the start up requires entering `npm start`, not `npm run serve`

**Comment by ljbennett62** [comment]
@jsolderitsch - updated the readme - thank you

**Comment by SatoshiNishishita** [comment]
Hello. I found the bugs web-app/server/app.js 27
We can not run createCar because of this bug.
Incorrect：var carsRecord = JSON.parse(JSON.parse(response));
correct：var carsRecord = JSON.parse(response);

Please modify this code.
Thank you.
