### ISSUE TITLE
How to consume 1 localhost log

### ISSUE THREAD

**Issue by FranciscoImanolSuarez** [IBM/fabcar-blockchain-sample#9]
Sorry for the inconvenience, I wanted to ask how I can bring 1 record only in the path localhost: 8081 / queryCalls that is, to be able to show in json the first record only

On the server in app.js is this GET route but I do not get an idea in chrome or postman how to consume only the first record
app.get ('/ queryAllCars', (req, res) => {
  network.queryAllCars ()
    .then ((response) => {
        var carsRecord = JSON.parse (response);
        res.send (carsRecord)
      });
})

**Comment by sandhya-nayak** [comment]
@FranciscoImanolSuarez A new GET route has been added to get a single record from the JSON:

E.g. http://localhost:8081/querySingleCar?key=CAR1 will show the JSON record corresponding to CAR with key "CAR1"
